name: Clone and Push to Org Repo

on:
  workflow_dispatch:

jobs: 
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push to destination repo (anshumaan1017/web-app-pipeline)
        env:
          DESTINATION_PAT: ${{ secrets.GHCR_TOKEN }}
        run: |
          git remote add destination https://${DESTINATION_PAT}@github.com/anshumaan1017/web-app-pipeline.git
          git push destination --all
          git push destination --tags
