name: Clone and Push to Org Repo

on:
  push: 
  workflow_dispatch:

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git user
        run: |
          git config --global user.name "anshumaan-10"
          git config --global user.email "anshumaansingh10jan@gmail.com"

      - name: Clone source repo
        run: git clone https://github.com/anshumaan-10/tic-tac-toe-devsecops-pipeline.git

      - name: Clone destination repo
        env:
          DESTINATION_PAT: ${{ secrets.GHCR_TOKEN }}
        run: git clone https://$DESTINATION_PAT@github.com/anshumaan1017/web-app-pipeline.git

      - name: Copy and push code
        env:
          DESTINATION_PAT: ${{ secrets.GHCR_TOKEN }}
        run: |
          cp -r tic-tac-toe-devsecops-pipeline/* web-app-pipeline/
          cd web-app-pipeline
          git add .
          git commit -m "S
